USE [!ESTY&TAMAR]
GO

/****** Object:  StoredProcedure [dbo].[TRUNCATE_MONTHLY_TABLES]    Script Date: 19/09/2019 15:05:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER PROC [dbo].[TRUNCATE_MONTHLY_TABLES] 
AS
BEGIN
TRUNCATE TABLE [SCHEDULE]
DELETE FROM [CLASSESFORGROUP]
DELETE FROM [GROUP]
DELETE FROM [ROOM]
DBCC CHECKIDENT ('!ESTY&TAMAR.dbo.ROOM',RESEED, 0)
DELETE FROM [CLASS]
DELETE FROM [PAYABSENCESFORTEACHER]
DELETE FROM [TEACHER]
DELETE FROM [SUBJECT]
END


GO


