//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dairy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dairy()
        {
            this.Classes = new HashSet<Class>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Num { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public bool IsGrouped { get; set; }
        public Nullable<int> OccasionId { get; set; }
        public Nullable<int> Reforma { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int Hour { get; set; }
        public Nullable<decimal> CalculateHours { get; set; }
        public Nullable<int> Cause { get; set; }
    
        public virtual Occasion Occasion { get; set; }
        public virtual OccasionType OccasionType { get; set; }
        public virtual Room Room { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class> Classes { get; set; }
        public virtual Group Group { get; set; }
    }
}
