//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Group()
        {
            this.Dairies = new HashSet<Dairy>();
            this.Schedules = new HashSet<Schedule>();
            this.Classes = new HashSet<Class>();
        }
    
        public int Num { get; set; }
        public Nullable<int> Teacher { get; set; }
        public Nullable<int> Subject { get; set; }
        public Nullable<int> Room { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<decimal> CalculateHours { get; set; }
        public Nullable<int> SchoolType { get; set; }
        public Nullable<int> Reforma { get; set; }
        public Nullable<int> PayAbsence { get; set; }
        public Nullable<int> HourType { get; set; }
        public Nullable<int> SubHourType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dairy> Dairies { get; set; }
        public virtual HourType HourType1 { get; set; }
        public virtual PayAbsence PayAbsence1 { get; set; }
        public virtual Reforma Reforma1 { get; set; }
        public virtual Room Room1 { get; set; }
        public virtual SchoolType SchoolType1 { get; set; }
        public virtual Subject Subject1 { get; set; }
        public virtual Teacher Teacher1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class> Classes { get; set; }
    }
}
